config/routes.rb
Shop::Application.routes.draw do

  resources :products
  get '/remove', :to => 'products#remove'

  resources :carts
  match 'carts/clear' => 'carts#clear', via: :get, as: :clear

  resources :checkouts

  root :to => 'products#index'

end

app/models/graph.rb
class Graph < ActiveRecord::Base
  attr_accessible :buy_with, :cart_with, :first_product, :second_product, :view_with
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title, :views, :price, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @sum = 0
    @products = Product.all
    @amount = Array.new(@products.length) { 0 }
    GetAmount()
  end

  def GetAmount
    if session[:in_cart] != nil
      @products.each do |product|
        session[:in_cart].each do |element|
          if product.id == element
            @amount[product.id - 1] += 1
          end
        end
      end
    end
  end

  def show
    session[:in_cart] = nil
    session[:total] = 0
    redirect_to products_path
  end

end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController

  require 'graph_manager'

  def index
    @username = "username"
  end

  def create
    render 'checkouts/show'
    if session[:bought] == nil
      session[:bought] = session[:in_cart]
    else
      session[:in_cart].each  do |element|
        session[:bought].push(element)
      end
    end
    session[:buy_with] = nil
    session[:buy_with] = session[:in_cart]
    session[:in_cart] = nil

    graph_update()
  end

  def graph_update
    if session[:buy_with] != nil and session[:buy_with].length > 1
      session[:buy_with].each do |first|
        session[:buy_with].each do |second|
          if first != second
            update_buy_graph(first, second)
            end
          end
        end
      end
  end

  def update_buy_graph(first, second)
    @graphManager = GraphManager.new
    myGraph = @graphManager.get_graph(first, second)
    myGraph.update_attribute(:buy_with, myGraph.buy_with + 1)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  require 'graph_manager'

  def index
    @products = Product.all

    #session.clear

    @buy_list = setup_array(:bought, @products)
    @cart = setup_array(:in_cart, @products)

    if session[:bought] != nil and session[:in_cart] != nil
      @view = Array.new(@products.length - @cart.length) { 0 }
      @products.each do |product|
        if @buy_list[product.id - 1] != product.id and product.id != @cart[product.id - 1]
          @view[product.id - 1] = product.id
        end
      end
    elsif session[:bought] != nil and session[:in_cart] == nil
      @view = Array.new(@products.length - @buy_list.length) { 0 }
      @products.each do |product|
        if @buy_list[product.id - 1] != product.id
          @view[product.id - 1] = product.id
        end
      end
    elsif session[:in_cart] != nil and session[:bought] == nil
      @view = Array.new(@products.length - @cart.length) { 0 }
      @products.each do |product|
        if product.id != @cart[product.id - 1]
          @view[product.id - 1] = product.id
        end
      end
    else
      @view = Array.new(@products.length) { 0 }
      @products.each do |product|
        @view[product.id - 1] = product.id
      end
    end

  end

  def setup_array(params, products)
    if session[params] != nil
      array = Array.new(session[params].length) { 0 }
      session[params].each do |element|
        if element == products[element - 1].id
          array[element - 1] = element
        end
      end
    end
    return array
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])

    if @product.save
      @graphManager = GraphManager.new
      @graphManager.graph_create()
      redirect_to @product
    else
      render new_product_path
    end
  end

  def show
    @product = Product.find(params[:id])
    session[:current_id] = @product.id

    view_session(@product)
    graph_update(:view_session, @product)
    graph_update(:in_cart, @product)

    get_all_elements(@product)

    @bought = check_list_type(:bought, @product)
    @remove = check_list_type(:in_cart, @product)

    @product.views += 1
    @product.update_attribute(:views, @product.views)
  end

  def get_all_elements(product)
    graph = Graph.find_all_by_first_product(product.id)
    graph.sort_by! { |element| element.cart_with }
    graph.reverse!

    four_ids = get_four_elements(graph)

    @in_cart = Array.new
    four_ids.each do |element|
      @in_cart.push(Product.find(element.second_product))
    end

    graph.clear
    graph = Graph.find_all_by_first_product(product.id)
    graph.sort_by! { |element| element.view_with }
    graph.reverse!

    four_ids = get_four_elements(graph)

    @view_with = Array.new
    four_ids.each do |element|
      @view_with.push(Product.find(element.second_product))
    end

    graph.clear
    graph = Graph.find_all_by_first_product(product.id)
    graph.sort_by! { |element| element.buy_with }
    graph.reverse!

    four_ids = get_four_elements(graph)

    @buy_with = Array.new
    four_ids.each do |element|
      @buy_with.push(Product.find(element.second_product))
    end
  end

  def get_four_elements(graph)
    ten_ids = Array.new(10)
    (0..9).each do |i|
      ten_ids[i] = (graph[i])
    end

    four_ids = Array.new(4)
    @newR = 0
    @prevR = Random.rand(9)
    4.times do |i|
      random_num()
      four_ids[i] = ten_ids[@newR]
    end

    return four_ids
  end

  def random_num
    @newR = Random.rand(9)
    if @newR == @prevR
      random_num()
    else
      @prevR = @newR
    end
  end

  def view_session(product)
    update_view = true
    if not session[:view_session].nil?
      session[:view_session].each do |element|
        if element == product.id
          update_view = false
          break
        end
      end
    end
    (session[:view_session] ||= []) << product.id if update_view
  end

  def graph_update(param, product)
    @graphManager = GraphManager.new
    if session[param] != nil and session[param].length > 1
      session[param].each do |element|
        if element == product.id
          session[param].each do |first|
            session[param].each do |second|
              if first != second
                if param == :in_cart
                  @graphManager.update_cart_graph(first, second)
                elsif param == :view_session
                  @graphManager.update_view_graph(first, second)
                end
              end
            end
          end
          break
        end
      end
    end
  end

  def check_list_type(params, product)
    my_bool = false
    if session[params] != nil
      session[params].each do |element|
        if element == product.id
          my_bool = true
          break
        end
      end
    end
    return my_bool
  end

  def remove
    array = Array.new
    session[:in_cart].each do |element|
      if element != session[:current_id]
        array.push(element)
      end
    end
    session[:in_cart] = nil
    session[:in_cart] = array

    session[:total] -= Product.find(session[:current_id]).price

    redirect_to products_path
  end

  def edit
    @product = Product.find(params[:id])
    (session[:in_cart] ||= []) << @product.id
    if session[:total] == nil
      session[:total] = 0
    end
    session[:total] = @product.price + session[:total]
    redirect_to products_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/index.html.erb
<h2>Корзина</h2>

<% if session[:in_cart] != nil %>

    <% cart_products = @products.select { |product| @amount[product.id - 1] > 0} %>

    <% i = 0 %>
    <% cart_products.each do |product| %>
            <% @sum += product.price %>
        <% if i % 6 == 0 %>
            <div class="row">
        <% end %>
        <div class="col-sm-2 product">
            <a href="<%= url_for product %>">
                <img src="/products/<%= product.id %>.png">
                <p class="catalog-product-name"><%= product.title %><br>
                <span class="catalog-price">(<%= number_to_currency product.price, unit: "грн.", format: "%n %u", delimiter: " " %>)</span></p>
            </a>
        </div>
        <% i += 1 %>
        <% if i % 6 == 0 or i == cart_products.length %>
            </div>
        <% end %>
    <% end %>

    <% session[:total] = @sum %>
    <h4>Итого: <%= number_to_currency session[:total], unit: "грн.", format: "%n %u", delimiter: " " %></h4>

    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <p><a href="<%= url_for clear_path %>" class="btn btn-danger cart-btn"><i class="glyphicon glyphicon-remove"></i> Очистить корзину</a></p>
            <p><a href="<%= url_for checkouts_path %>" class="btn btn-success cart-btn"><i class="glyphicon glyphicon-ok"></i> Оплатить</a></p>
        </div>
    </div>

<% else %>

    <h3>Ваша корзина пуста. Выберите товары <%= link_to 'здесь', products_path %>.</h3>

<% end %>

<p class="text-center"><a href="<%= url_for products_path %>">&larr; Вернуться к каталогу</a></p>

app/views/carts/show.html.erb
<h1>Redirecting...</h1>

app/views/checkouts/index.html.erb
<h2>Оплата</h2>

<% if session[:in_cart] %>

<%= form_for @username do |form| %>
  <h3>Сумма: <%= number_to_currency session[:total], unit: "грн.", format: "%n %u", delimiter: " " %></h3>
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
      <input type="text" placeholder="Ваше имя">
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
      <button class="submit-button">Оплатить</button>
    </div>
  </div>
<% end %>

<% else %>

<h3>Ваша корзина пуста. Выберите товары <%= link_to 'здесь', products_path %>.</h3>

<% end %>

app/views/checkouts/show.html.erb
<h2>Успешно оплачено!</h2>
<h3><%= link_to 'Вернуться к каталогу', products_path %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DaedraShop &ndash; интернет-магазин оружия и доспехов из The Elder Scrolls IV: Oblivion</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if not session[:total] %>
<% session[:total] = 0 %>
<% end %>

<nav class="navbar navbar-inverse navbar-fixed-top navbar-custom" role="navigation" data-spy="affix" data-offset-top="10">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/products"><span class="navbar-brand">DaedraShop</span></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/products"><i class="glyphicon glyphicon-th"></i> Каталог продукции</a></li>
        <li><a href="/carts"><i class="glyphicon glyphicon-shopping-cart"></i> Корзина <span class="badge"><%= session[:in_cart].length if session[:in_cart] %></span></a></li>
        <li><a href="/checkouts"><i class="glyphicon glyphicon-credit-card"></i> Совершить покупку</a></li>
      </ul>
      </ul>
    </div>
  </div>
</nav>

<div class="container container-fluid page-wrapper">
  <h1>DaedraShop</h1>
  <div class="row">
    <div class="col-sm-9">
      <%= yield %>
    </div>
    <div class="col-sm-3">
      <div class="side-float cart-float">
        <h4><i class="glyphicon glyphicon-shopping-cart"></i> Корзина</h4>
        <% if session[:in_cart] %>
          <p>Количество товаров: <%= session[:in_cart].length %></p>
          <p>Сумма: <%= number_to_currency session[:total], unit: "грн.", format: "%n %u", delimiter: " " %></p>
          <p><a href="/carts">Перейти к корзине</a></p>
          <p><a href="/checkouts">Оплатить</a></p>
        <% else %>
          <p>Ваша корзина пуста!</p>
          <p><a href="/products">Перейти к каталогу продукции</a></p>
        <% end %>
      </div>
      <div class="side-float">
        <h5><i class="glyphicon glyphicon-th"></i> <a href="/products">Каталог продукции</a></h5>
      </div>
    </div>
  </div>
</div>

<div class="push"></div>

<footer>
  <div class="container">
    &copy; True Web Warriors of Code and Magic, 2014
  </div>
</footer>

</body>
</html>

app/views/products/edit.html.erb
<h1>Redirecting...</h1>

app/views/products/index.html.erb
<h2>Каталог продукции</h2>

<div class="container-fluid">
<% if @buy_list != nil %>
    <h4>Уже куплено:</h4>
    <% i = 0 %>
    <% tmp_buy_list = @buy_list.select { |element| element.to_i > 0 } %>
    <% tmp_buy_list.each do |element| %>
        <% if element.to_i > 0 %>
            <% if i % 6 == 0 %>
                <div class="row">
            <% end %>
            <div class="col-sm-2 product">
                <a href="<%= url_for @products[element - 1] %>">
                    <img src="/products/<%= @products[element - 1].id %>.png">
                    <p class="catalog-product-name"><%= @products[element - 1].title %><br>
                    <span class="catalog-price">(<%= number_to_currency @products[element - 1].price, unit: "грн.", format: "%n %u", delimiter: " " %>)</span></p>
                </a>
            </div>
            <% i += 1 %>
            <% if i % 6 == 0 or i == tmp_buy_list.length %>
                </div>
            <% end %>
        <% end %>
    <% end %>
<% end %>
</div>

<div class="container-fluid">
<% if @view != nil %>
    <h4>Доступные товары:</h4>
    <% i = 0 %>
    <% @view_list = @products.select { |product| product.id == @view[product.id - 1] }.sort_by do |element| %>
        <% element[:views] %>
    <% end %>
    <% @view_list.reverse! %>

    <% @view_list.each do |product| %>
        <% if i % 6 == 0 %>
            <div class="row">
        <% end %>
        <div class="col-sm-2 product">
            <a href="<%= url_for product %>">
                <img src="/products/<%= product.id %>.png">
                <p class="catalog-product-name"><%= product.title %><br>
                    <span class="catalog-price">(<%= number_to_currency product.price, unit: "грн.", format: "%n %u", delimiter: " " %>)</span></p>
            </a>
        </div>
        <% i += 1 %>
        <% if i % 6 == 0 or i == @view_list.length %>
            </div>
        <% end %>
    <% end %>
<% end %>
</div>

<div class="container-fluid">
<% if @cart != nil %>
    <h4>Добавлено в корзину:</h4>
    <% i = 0 %>
    <% tmp_cart = @cart.select { |element| element.to_i > 0 } %>
    <% tmp_cart.each do |element| %>
        <% if element.to_i > 0 %>
            <% if i % 6 == 0 %>
                <div class="row">
            <% end %>
            <div class="col-sm-2 product">
                <a href="<%= url_for @products[element - 1] %>">
                    <img src="/products/<%= @products[element - 1].id %>.png">
                    <p class="catalog-product-name"><%= @products[element - 1].title %><br>
                    <span class="catalog-price">(<%= number_to_currency @products[element - 1].price, unit: "грн.", format: "%n %u", delimiter: " " %>)</span></p>
                </a>
            </div>
            <% i += 1 %>
            <% if i % 6 == 0 or i == tmp_cart.length %>
                </div>
            <% end %>
        <% end %>
    <% end %>
<% end %>
</div>

app/views/products/new.html.erb
<h2>Dev only</h2>
<h3>Product setup</h3>
<%= form_for @product do |form| %>
    <p><%= form.label :title %></p>
    <%= form.text_field :title %>
    <p><%= form.label :views %></p>
    <%= form.text_field :views %>
    <p><%= form.label :price %></p>
    <%= form.text_field :price %>
    <p><%= form.label :description %></p>
    <%= form.text_area :description %>
    <br>
    <p><%= form.submit %></p>
<% end %>
<p><%= link_to 'Back', products_path %></p>

app/views/products/show.html.erb
<h2><%= @product.title %></h2>

<div class="row">
    <div class="col-sm-4 text-center">
        <img class="big-image" src="/products/<%= @product.id %>.png">
    </div>
    <div class="col-sm-8">
        <div>
            <p class="product-price pull-left">Цена: <%= number_to_currency @product.price, unit: "грн.", format: "%n %u", delimiter: " " %></p>
            <p class="pull-right">
                <% if @remove %>
                    <i class="glyphicon glyphicon-ok"></i> Уже в корзине <a href="<%= url_for remove_path %>" class="delete-link">(<i class="glyphicon glyphicon-remove"></i> Удалить)</a>
                <% else %>
                    <a href="<%= url_for edit_product_path %>"><i class="glyphicon glyphicon-plus"></i> Добавить в корзину</a>
                <% end %>
            </p>
        </div>
        <div class="clearfix"></div>
        <p class="description">
            <%= @product.description %>
        </p>
        <p>Просмотров: <%= @product.views %></p>
        <br>
        
        <h4>Смотрите также:</h4>
        <% if @buy_with %>
            <div class="row">
                <% @buy_with.each do |element| %>
                    <div class="col-sm-3 product">
                        <a href="<%= url_for element %>">
                            <img src="/products/<%= element.id %>.png">
                            <p class="catalog-product-name"><%= element.title %><br>
                            <span class="catalog-price">(<%= number_to_currency element.price, unit: "грн.", format: "%n %u", delimiter: " " %>)</span></p>
                        </a>
                    </div>
                <% end %>
            </div>
        <% end %>
        <% if @view_with %>
            <div class="row">
                <% @view_with.each do |element| %>
                    <div class="col-sm-3 product">
                        <a href="<%= url_for element %>">
                            <img src="/products/<%= element.id %>.png">
                            <p class="catalog-product-name"><%= element.title %><br>
                            <span class="catalog-price">(<%= number_to_currency element.price, unit: "грн.", format: "%n %u", delimiter: " " %>)</span></p>
                        </a>
                    </div>
                <% end %>
            </div>
        <% end %>
        <% if @in_cart %>
            <div class="row">
                <% @in_cart.each do |element| %>
                    <div class="col-sm-3 product">
                        <a href="<%= url_for element %>">
                            <img src="/products/<%= element.id %>.png">
                            <p class="catalog-product-name"><%= element.title %><br>
                            <span class="catalog-price">(<%= number_to_currency element.price, unit: "грн.", format: "%n %u", delimiter: " " %>)</span></p>
                        </a>
                    </div>
                <% end %>
            </div>
        <% end %>

        <br>

        <p>
        <% if @remove %>
            <a href="<%= url_for remove_path %>" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> Убрать из корзины</a>
        <% else %>
            <a href="<%= url_for edit_product_path %>" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> Добавить в корзину</a>
        <% end %>
        </p>

        <p><a href="<%= url_for products_path %>">&larr; Вернуться к каталогу</a></p>
    </div>
</div>